image: docker:latest
services:
  - docker:dind


stages:
  - build
  - test
  - package
  - deploy


variables:
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: 431611288834.dkr.ecr.us-east-1.amazonaws.com/continuous_delivery
    IMAGE_TAG: ${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}
    AWS_REGION: us-east-1



###########################
# Building
###########################
build-jar:
  stage: build
  image: openjdk:8-jdk
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script: "./gradlew assemble"
  artifacts:
    paths:
      - backend/build/libs/*.jar
    expire_in: 1 week
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build/nodejs
      - frontend/customer/node_modules
      - frontend/manager/node_modules


test-unit:
  stage: test
  image: openjdk:8-jdk
  variables:
    POSTGRES_HOST: "postgres"
    POSTGRES_DB: "continuous-delivery"
    POSTGRES_USER: "continuous-delivery"
    POSTGRES_PASSWORD: "$5CstQcmYk0E"
    RABBITMQ_HOST: "rabbitmq"
    RABBITMQ_DEFAULT_USER: "continuous-delivery"
    RABBITMQ_DEFAULT_PASS: "3YceZ8^15H59"
    RABBITMQ_DEFAULT_VHOST: "/"
  services:
    - name: postgres
      alias: $POSTGRES_HOST
    - name: rabbitmq
      alias: $RABBITMQ_HOST
  script:
    - ./gradlew check
    - cat backend/build/reports/jacoco/test/html/index.html
  artifacts:
      when: always
      paths:
        - backend/build/reports/tests/test/
      expire_in: 1 week



###########################
# Packaging
###########################
.registry-auth-script: &registry_auth
  - |
    docker run --rm \
               -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
               -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
               zensoftdevops/aws-cli \
               aws ecr get-login --no-include-email --region ${AWS_REGION} | sh


package-docker:
  stage: package
  before_script: *registry_auth
  script:
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f docker/Dockerfile .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}
  only:
    - mvp
    - sprint
    - staging
    - master



###########################
# Deployment
###########################
.prepare-key-script: &prepare_key
  - apk add --no-cache openssh-client
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts


.deploy-to-host-script: &deploy_to_host
  - |
    ssh ${DEPLOY_USER}@${DEPLOY_HOST} "
      docker run --rm \
                 -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
                 -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
                 zensoftdevops/aws-cli \
                 aws ecr get-login --no-include-email --region ${AWS_REGION} | sh
    "
  - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "docker pull ${IMAGE_NAME}:${IMAGE_TAG}"
  - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "bash -s" < docker/stop_instance.sh ${CONTAINER_NAME}
  - |
    ssh ${DEPLOY_USER}@${DEPLOY_HOST} "
      docker run -it -d --name ${CONTAINER_NAME} --restart=always \
                 --net inhouse-lan -p ${CONTAINER_EXT_PORT}:8080 \
                 -e "POSTGRES_HOST=${POSTGRES_HOST}" \
                 -e "POSTGRES_DB=${POSTGRES_DB}" \
                 -e "POSTGRES_USER=${POSTGRES_USER}" \
                 -e "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" \
                 -e "RABBITMQ_HOST=${RABBITMQ_HOST}" \
                 -e "RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}" \
                 -e "RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}" \
                 -e "RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}" \
                 ${IMAGE_NAME}:${IMAGE_TAG}
    "


deploy-production:
  stage: deploy
  variables:
    DEPLOY_KEY: $DEPLOY_PRODUCTION_KEY
    DEPLOY_USER: ubuntu
    DEPLOY_HOST: 34.238.175.66
    CONTAINER_NAME: continuous_delivery
    CONTAINER_EXT_PORT: 8899
    POSTGRES_HOST: inhouse.db.zensoft.io:5432
    POSTGRES_DB: continuous_delivery
    POSTGRES_USER: inhouse
    POSTGRES_PASSWORD: $PRODUCTION_POSTGRES_PASSWORD
    RABBITMQ_HOST: inhouse.rabbitmq.zensoft.io
    RABBITMQ_DEFAULT_USER: admin
    RABBITMQ_DEFAULT_PASS: $PRODUCTION_RABBITMQ_PASSWORD
    RABBITMQ_DEFAULT_VHOST: /
    APPLICATION_DOMAIN: https://cd.zensoft.io
  before_script: *prepare_key
  script: *deploy_to_host
  only:
    - mvp
#    - master


deploy-dev:
  stage: deploy
  variables:
    DEPLOY_USER: inhouse
    DEPLOY_HOST: 192.168.89.243
    CONTAINER_NAME: continuous_delivery
    CONTAINER_EXT_PORT: 8899
    POSTGRES_HOST: 192.168.89.243
    POSTGRES_DB: continuous_delivery
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 8%zyWINF
    RABBITMQ_HOST: 192.168.89.243
    RABBITMQ_DEFAULT_USER: admin
    RABBITMQ_DEFAULT_PASS: inhouse312!
    RABBITMQ_DEFAULT_VHOST: /
    APPLICATION_DOMAIN: http://cd.zensoft.lan
    DEPLOY_KEY: $DEPLOY_DEV_KEY
  before_script: *prepare_key
  script: *deploy_to_host
  only:
    - sprint
